Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [9]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
## нет ##

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [14]:
np.random.randn(3, 4)

array([[ 2.27818466,  1.10255524, -0.56162013, -0.83195348],
       [-0.56970237,  0.21815859, -0.88416339, -0.45737088],
       [ 1.07274474, -0.62235326, -0.54928497,  0.33934105]])

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [15]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [16]:
b = np.arange(20, 0, -2).reshape(10, 1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Отличается размера массива (shape) и другая индексация, например, чтобы получить 18:

In [17]:
b[1][0]

18

In [18]:
a[1]

18

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [19]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print(a)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [23]:
v = np.concatenate((a, b), axis=0)
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [25]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [28]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [29]:
B.shape

(4, 4)

In [30]:
np.linalg.inv(B)

LinAlgError: Singular matrix

Определитель равен нулю - вырожденная матрица

In [32]:
np.linalg.det(B)

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [36]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [44]:
c = np.random.randint(0, 16, 16)
c

array([ 6, 11, 12,  7, 14,  2, 13,  0,  3,  1,  7,  3,  1, 13,  5,  5])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [48]:
C = c.reshape(4, 4)
C

array([[ 6, 11, 12,  7],
       [14,  2, 13,  0],
       [ 3,  1,  7,  3],
       [ 1, 13,  5,  5]])

In [50]:
D = B + C * 10
D

array([[ 65, 124, 143, 102],
       [154,  70, 216, 122],
       [ 53,  96, 219, 242],
       [ 42, 252, 262, 352]])

In [51]:
np.linalg.det(D)

-120236800.00000031

In [52]:
np.linalg.matrix_rank(D)

4

In [53]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.02633936,  0.02097195, -0.02208908,  0.01554998],
       [ 0.0070278 , -0.00127482, -0.00802117,  0.00391993],
       [ 0.03031085, -0.01554799,  0.02349231, -0.01954543],
       [-0.02444942,  0.00998297, -0.00910769,  0.01272722]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [56]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[0, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [62]:
E = np.where(D_inv == 1, B, C)
E

array([[  6,  14,  12,  32],
       [ 14,   2,  13, 122],
       [ 23,   1, 149,   3],
       [  1, 122,   5, 302]])